/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    resume_data: ResumeData;
    resume_skills: ResumeSkill;
    resume_languages: ResumeLanguage;
    resume_technologies: ResumeTechnology;
    resume_tools: ResumeTool;
    resume_setups: ResumeSetup;
    resume_prompts: ResumePrompt;
    resume_imports: ResumeImport;
    resume_exports: ResumeExport;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    resume_setups: {
      exports: 'resume_exports';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    resume_data: ResumeDataSelect<false> | ResumeDataSelect<true>;
    resume_skills: ResumeSkillsSelect<false> | ResumeSkillsSelect<true>;
    resume_languages: ResumeLanguagesSelect<false> | ResumeLanguagesSelect<true>;
    resume_technologies: ResumeTechnologiesSelect<false> | ResumeTechnologiesSelect<true>;
    resume_tools: ResumeToolsSelect<false> | ResumeToolsSelect<true>;
    resume_setups: ResumeSetupsSelect<false> | ResumeSetupsSelect<true>;
    resume_prompts: ResumePromptsSelect<false> | ResumePromptsSelect<true>;
    resume_imports: ResumeImportsSelect<false> | ResumeImportsSelect<true>;
    resume_exports: ResumeExportsSelect<false> | ResumeExportsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    openai: Openai;
  };
  globalsSelect: {
    openai: OpenaiSelect<false> | OpenaiSelect<true>;
  };
  locale: 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: 'admin' | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_data".
 */
export interface ResumeData {
  id: number;
  owner?: (number | null) | User;
  name?: string | null;
  profile?: {
    avatar?: (number | null) | Media;
    suffix?: string | null;
    firstName?: string | null;
    middleName?: string | null;
    lastName?: string | null;
    contacts?:
      | {
          type?: ('text' | 'email' | 'phone' | 'link') | null;
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    headline?: string | null;
    summary?: string | null;
  };
  experiences?:
    | {
        jobTitle?: string | null;
        type?: ('fullTime' | 'partTime' | 'freelance' | 'contract' | 'internship') | null;
        company?: string | null;
        location?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        skills?: (number | ResumeSkill)[] | null;
        tools?: (number | ResumeTool)[] | null;
        technologies?: (number | ResumeTechnology)[] | null;
        customBlocks?:
          | {
              blockTitle?: string | null;
              items?:
                | {
                    item?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        institution?: string | null;
        degree?: string | null;
        fieldOfStudy?: string | null;
        location?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        customBlocks?:
          | {
              blockTitle?: string | null;
              items?:
                | {
                    item?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  skills?: (number | ResumeSkill)[] | null;
  projects?:
    | {
        project?: string | null;
        role?: string | null;
        description?: string | null;
        technologies?: (number | ResumeTechnology)[] | null;
        links?:
          | {
              link?: string | null;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        customBlocks?:
          | {
              blockTitle?: string | null;
              items?:
                | {
                    item?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language?: (number | null) | ResumeLanguage;
        level?: ('beginner' | 'intermediate' | 'advanced' | 'native') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes Skills are used to track the skills of the resumes of the users and are used as input data for the AI agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_skills".
 */
export interface ResumeSkill {
  id: number;
  skill?: string | null;
  category?: ('programming' | 'design' | 'marketing' | 'sales' | 'business' | 'finance' | 'education' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes Tools are used to track the tools of the resumes of the users and are used as input data for the AI agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_tools".
 */
export interface ResumeTool {
  id: number;
  tool?: string | null;
  category?: ('financial' | 'marketing' | 'sales' | 'business' | 'finance' | 'education' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes Technologies are used to track the technologies of the resumes of the users and are used as input data for the AI agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_technologies".
 */
export interface ResumeTechnology {
  id: number;
  technology?: string | null;
  type?:
    | (
        | 'framework'
        | 'language'
        | 'library'
        | 'protocol'
        | 'platform'
        | 'database'
        | 'cloud'
        | 'devops'
        | 'testing'
        | 'security'
        | 'ai'
        | 'machine_learning'
        | 'data_science'
        | 'big_data'
        | 'blockchain'
        | 'internet_of_things'
        | 'robotics'
        | 'other'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes Languages are used to track the languages of the resumes of the users and are used as input data for the AI agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_languages".
 */
export interface ResumeLanguage {
  id: number;
  language?: string | null;
  code?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes Setups are used to track the setups of the resumes of the users and are used as input data for the AI agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_setups".
 */
export interface ResumeSetup {
  id: number;
  owner?: (number | null) | User;
  name?: string | null;
  description?: string | null;
  resumeData?: (number | null) | ResumeData;
  resumePrompt?: (number | null) | ResumePrompt;
  exportFormat?: 'markdown' | null;
  targetCountry?: string | null;
  targetLanguage?: string | null;
  targetJobTitle?: string | null;
  targetPosition?: string | null;
  options?: {
    optmizedFor?: ('ats' | 'hr' | 'both') | null;
  };
  exports?: {
    docs?: (number | ResumeExport)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes Prompts are used to track the prompts of the resumes of the users and are used as input data for the AI agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_prompts".
 */
export interface ResumePrompt {
  id: number;
  name?: string | null;
  systemPrompt?: string | null;
  prompt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes Exports are used to track the exports of the resumes of the users and are used as input data for the AI agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_exports".
 */
export interface ResumeExport {
  id: number;
  owner?: (number | null) | User;
  name?: string | null;
  status?: ('pending' | 'completed' | 'failed') | null;
  resumeSetup?: (number | null) | ResumeSetup;
  exportType?: 'plainText' | null;
  plainText?: {
    prompt?: string | null;
    systemPrompt?: string | null;
    content?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Resumes Imports are used to track the imports of the resumes of the users and are used as input data for the AI agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_imports".
 */
export interface ResumeImport {
  id: number;
  owner?: (number | null) | User;
  name?: string | null;
  importType?: 'plainText' | null;
  plainText?: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  resumeData?: (number | null) | ResumeData;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'resume_data';
        value: number | ResumeData;
      } | null)
    | ({
        relationTo: 'resume_skills';
        value: number | ResumeSkill;
      } | null)
    | ({
        relationTo: 'resume_languages';
        value: number | ResumeLanguage;
      } | null)
    | ({
        relationTo: 'resume_technologies';
        value: number | ResumeTechnology;
      } | null)
    | ({
        relationTo: 'resume_tools';
        value: number | ResumeTool;
      } | null)
    | ({
        relationTo: 'resume_setups';
        value: number | ResumeSetup;
      } | null)
    | ({
        relationTo: 'resume_prompts';
        value: number | ResumePrompt;
      } | null)
    | ({
        relationTo: 'resume_imports';
        value: number | ResumeImport;
      } | null)
    | ({
        relationTo: 'resume_exports';
        value: number | ResumeExport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_data_select".
 */
export interface ResumeDataSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  profile?:
    | T
    | {
        avatar?: T;
        suffix?: T;
        firstName?: T;
        middleName?: T;
        lastName?: T;
        contacts?:
          | T
          | {
              type?: T;
              value?: T;
              label?: T;
              id?: T;
            };
        headline?: T;
        summary?: T;
      };
  experiences?:
    | T
    | {
        jobTitle?: T;
        type?: T;
        company?: T;
        location?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        skills?: T;
        tools?: T;
        technologies?: T;
        customBlocks?:
          | T
          | {
              blockTitle?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  education?:
    | T
    | {
        institution?: T;
        degree?: T;
        fieldOfStudy?: T;
        location?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        customBlocks?:
          | T
          | {
              blockTitle?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  skills?: T;
  projects?:
    | T
    | {
        project?: T;
        role?: T;
        description?: T;
        technologies?: T;
        links?:
          | T
          | {
              link?: T;
              label?: T;
              id?: T;
            };
        customBlocks?:
          | T
          | {
              blockTitle?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_skills_select".
 */
export interface ResumeSkillsSelect<T extends boolean = true> {
  skill?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_languages_select".
 */
export interface ResumeLanguagesSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_technologies_select".
 */
export interface ResumeTechnologiesSelect<T extends boolean = true> {
  technology?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_tools_select".
 */
export interface ResumeToolsSelect<T extends boolean = true> {
  tool?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_setups_select".
 */
export interface ResumeSetupsSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  description?: T;
  resumeData?: T;
  resumePrompt?: T;
  exportFormat?: T;
  targetCountry?: T;
  targetLanguage?: T;
  targetJobTitle?: T;
  targetPosition?: T;
  options?:
    | T
    | {
        optmizedFor?: T;
      };
  exports?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_prompts_select".
 */
export interface ResumePromptsSelect<T extends boolean = true> {
  name?: T;
  systemPrompt?: T;
  prompt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_imports_select".
 */
export interface ResumeImportsSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  importType?: T;
  plainText?:
    | T
    | {
        content?: T;
      };
  resumeData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_exports_select".
 */
export interface ResumeExportsSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  status?: T;
  resumeSetup?: T;
  exportType?: T;
  plainText?:
    | T
    | {
        prompt?: T;
        systemPrompt?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "openai".
 */
export interface Openai {
  id: number;
  general: {
    model: 'gpt-5' | 'gpt-4.1';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "openai_select".
 */
export interface OpenaiSelect<T extends boolean = true> {
  general?:
    | T
    | {
        model?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}